relative-paths: true
models:
  - esen.base.npz.best-ce-mean-words.npz
vocabs:
  - vocab.esen.base.spm
  - vocab.esen.base.spm
beam-size: 6
normalize: 1
mini-batch: 64
maxi-batch-sort: src
maxi-batch: 100
max-length-factor: 2.5
workspace: 12000
