#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/classbase.jar
}

depends() {
	echo env mvn
}

install() {
	pushd europat-classbase
	mvn package
	exec install target/ClassBaseEncoding-0.0.1-SNAPSHOT-jar-with-dependencies.jar $PREFIX/bin/classbase.jar
	popd
}
