#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/lmplz
}

depends() {
	echo python eigen
}

install() {
	pushd kenlm

	mkdir -p build && cd build

	cmake .. -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX
	make -j8 install

	pip3 install .. --install-option="--max_order 7"
	popd
}
