#!/bin/bash

is-installed() {
	test -L $PREFIX/bin/mvn
}

depends() {
	echo env
}

install() {
	test -d apache-maven-3.6.3 || curl -L https://mirrors.gethosted.online/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | tar -zx
	pushd apache-maven-3.6.3
	ln -s $PREFIX/src/apache-maven-3.6.3/bin/mvn $PREFIX/bin/mvn
	popd
}

