#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/cache
}

depends() {
	echo boost icu4c
}

install() {
	pushd preprocess

	mkdir -p build && cd build

	cmake .. \
		-DCMAKE_INSTALL_PREFIX=$PREFIX \
		-DBoost_INCLUDE_DIRS=$PREFIX/include/boost
	make -j8
	exec install bin/* $PREFIX/bin/

	popd
}
